# Generated by Django 3.2.3 on 2021-05-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
