# Generated by Django 3.2.3 on 2021-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_document_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
